name: 'Build godot'
description: 'Build godot'

inputs:
  channel:
    description: 'Channel to build'
    required: true
    default: 'windows'
  output:
    description: 'Output directory'
    required: true
  game-folder:
    description: 'Directory of the game'
    default: '.'
  password:
    description: 'Password for the files'
    required: false

runs:
  using: "composite"
  steps:
    - id: game-name
      run: |
        NAME="$(cat $FOLDER/project.godot | grep config/name | awk -F'"' '{print $2}')"
        echo "game=$NAME" >> $GITHUB_OUTPUT
      shell: bash
      env:
        FOLDER: ${{ inputs.game-folder }}
    - name: Build
      id: build
      run: |
        mkdir -v -p $OUTPUT/$CHANNEL

        EXT=""
        if [ "$CHANNEL" = "web" ]; then
          EXT=".html"
        elif [ "$CHANNEL" = "linux" ]; then
          EXT=".x86_64"
        elif [ "$CHANNEL" = "windows" ]; then
          EXT=".exe"
        fi

        godot --export-release --headless --path $FOLDER $CHANNEL "$(pwd)/$OUTPUT/$CHANNEL/main$EXT"
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        OUTPUT: ${{ inputs.output }}
        FOLDER: ${{ inputs.game-folder }}

    - uses: kuma-gee/action-godot/7zip@main
      with:
        folder: "${{ inputs.output }}/${{ inputs.channel }}/*"
        password: ${{ inputs.password }}
        output: ${{ inputs.output }}/${{ steps.game-name.outputs.game }}-${{ inputs.channel }}.7z