name: 'Build godot'
description: 'Build godot'

inputs:
  channel:
    description: 'Channel to build'
    required: true
    default: 'win'
  output:
    description: 'Output directory'
    required: true
  game-folder:
    description: 'Directory of the game'
    default: '.'
  password:
    description: 'Password for the files'
    required: false

runs:
  using: "composite"
  steps:
    - name: Build
      id: build
      run: |
        mkdir -v -p $OUTPUT/$CHANNEL

        EXT=""
        if [ "$CHANNEL" = "web" ]; then
          EXT=".html"
        elif [ "$CHANNEL" = "linux" ]; then
          EXT=".x86_64"
        elif [ "$CHANNEL" = "windows" ]; then
          EXT=".exe"
        fi

        NAME="$(cat $FOLDER/project.godot | grep config/name | awk -F'"' '{print $2}')"
        echo "game=$NAME" >> $GITHUB_OUTPUT

        godot --export-release --headless --path $FOLDER $CHANNEL "$(pwd)/$OUTPUT/$CHANNEL/$NAME$EXT"
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        OUTPUT: ${{ inputs.output }}
        FOLDER: ${{ inputs.game-folder }}

    - run: |
        cd $OUTPUT
        mv $CHANNEL $GAME
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        OUTPUT: ${{ inputs.output }}
        GAME: ${{ steps.build.outputs.game }}
    
    - uses: kuma-gee/action-godot/7zip@main
      with:
        folder: "${{ inputs.output }}/${{ steps.build.outputs.game }}"
        password: ${{ inputs.password }}
        output: ${{ inputs.output }}/${{ steps.build.outputs.game }}-${{ inputs.channel }}.7z