name: 'Build godot'
description: 'Build godot'

inputs:
  channel:
    description: 'Channel to build'
    required: true
    default: 'win'
  output:
    description: 'Output directory'
    required: true
  name:
    description: 'Name of the game'
    required: true
  password:
    description: 'Password for the archive file'
  game-folder:
    description: 'Directory of the game'
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Build
      run: |
        mkdir -v -p $OUTPUT/$CHANNEL

        EXT=""
        if [ "$CHANNEL" = "web" ]; then
          EXT=".html"
        elif [ "$CHANNEL" = "linux" ]; then
          EXT=".x86_64"
        elif [ "$CHANNEL" = "windows" ]; then
          EXT=".exe"
        fi

        godot --export-release --headless --path $FOLDER $CHANNEL "$(pwd)/$OUTPUT/$CHANNEL/$NAME$EXT"
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        OUTPUT: ${{ inputs.output }}
        NAME: ${{ inputs.name }}
        FOLDER: ${{ inputs.game-folder }}

    - run: |
        cd $OUTPUT
        mv $CHANNEL $GAME
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        OUTPUT: ${{ inputs.output }}
        GAME: ${{ inputs.name }}
    
    - run: ls
      shell: bash
    - run: ls $OUTPUT
      shell: bash
      env:
        OUTPUT: ${{ inputs.output }}

    - uses: kuma-gee/action-godot/7zip
      with:
        folder: "${{ inputs.output }}/${{ inputs.name}}"
        password: ${{ inputs.password }}
        output: ${{ inputs.output }}/${{ inputs.name }}-${{ inputs.channel }}.7z