name: 'Godot Build'
description: 'Build godot project'
inputs:
  version:
    description: 'Godot version'
    required: true
    default: '4.3'
  output:
    description: 'Output folder'
    required: true
    default: 'build'
  channel:
    description: 'Channel to build'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Templates
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      shell: bash
      env:
        GODOT_VERSION: ${{ inputs.version }}

    - name: Build
      run: |
        mkdir -v -p $OUTPUT/$CHANNEL
        godot --export-release --headless $CHANNEL
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        OUTPUT: ${{ inputs.output }}
