name: 'Setup templates'
description: 'Setup default godot templates and optionally custom templates with encryption'
inputs:
  channel:
    description: 'Channel to build'
    required: true
    default: 'windows'
  version:
    description: 'Godot Version'
    default: '4.3'
  encryption-key:
    description: 'Encryption key'
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/export_templates/${VERSION}.stable ~/.local/share/godot/export_templates/${VERSION}.stable
      shell: bash
      env:
        VERSION: ${{ inputs.version }}

    - uses: dsaltares/fetch-gh-release-asset@master
      id: release-asset
      continue-on-error: true
      with:
        version: 'tags/template-${{ inputs.version }}'
        file: template_release\\.${{ inputs.channel }}.*
        target: custom_templates/
        regex: true
      
    - run: |
        FILE=$(ls custom_templates/template.release.${{ inputs.channel }}*)

        sed -e "/custom_template\/release/ s/\".*\"/\"custom_templates/$FILE\"/" -i export_presets.cfg
        sed -e "/script_encryption_key/ s/\".*\"/\"$KEY\"/"  -i .godot/export_credentials.cfg
      shell: bash
      env:
        KEY: ${{ inputs.encryption-key }}
      if: steps.release-asset.conclusion == 'success'