name: 'Setup templates'
description: 'Setup godot templates'
inputs:
  version:
    description: 'Godot Version'
    default: '4.3'
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/export_templates/${VERSION}.stable ~/.local/share/godot/export_templates/${VERSION}.stable
      shell: bash
      env:
        VERSION: ${{ inputs.version }}

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: 'tags/template-${{ inputs.version }}'
        file: godot\\..*
        target: custom_templates/
        regex: true