# TODO:
name: Android Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GAME: godot-template
  GODOT_VERSION: 4.3
  STEAM_APP: 430

jobs:
  release:
    runs-on: ubuntu-latest
    needs: generate-password
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4

      - name: Package builds
        run: |
          cd build
          mv $CHANNEL $GAME
          zip -e -r $GAME-$CHANNEL.zip $GAME -P $PASSWORD
        env:
          PASSWORD: ${{ needs.generate-password.outputs.password }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.channel }}
          path: build/**/*.zip