name: Github release with changelog and discord notification

on:
  workflow_call:
    inputs:
      artifact:
        description: 'Artifact patterns to download'
        required: true
        type: string
      name:
        description: 'Name of the release'
        type: string
        default: ''
      add-changelog:
        description: 'Add changelog to release'
        type: boolean
        default: false
    secrets:
      discord-webhook:
        required: false


jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./changelog

      - run: echo $CHANGELOG > CHANGELOG.md
        if: ${{ inputs.add-changelog }}
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}

      - uses: actions/download-artifact@v4
        with:
          pattern: release-*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          prerelease: false
          files: |
            **/*.zip
            **/*.aab

      - name: Successful release!
        if: success() && secrets.discord-webhook
        uses: ./discord
        with:
          discord-webhook: ${{ secrets.discord-webhook }}
          title: "${{ inputs.name }} - New Release ${{ github.ref }}"
          message: "${{ steps.changelog.outputs.changelog }}"

      - name: Failed release!
        if: failure() && secrets.discord-webhook
        uses: ./discord
        with:
          discord-webhook: ${{ secrets.discord-webhook }}
          title: "${{ inputs.name }} - Failed Release ${{ github.ref }}"
          message: "See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"