name: Github release with changelog and discord notification

on:
  workflow_call:
    inputs:
      artifact:
        description: 'Artifact patterns to download'
        required: true
        type: string
      name:
        description: 'Name of the release'
        type: string
        default: ''
      branch:
        description: 'Branch to release'
        type: string
        default: ''
      add-changelog:
        description: 'Add changelog to release'
        type: boolean
        default: true
      notify:
        description: 'Notify on discord'
        type: boolean
        default: true
    secrets:
      discord-webhook:
        required: true
      password:
        description: 'Password for the files'
        required: false

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./changelog

      - run: echo $CHANGELOG > CHANGELOG.md
        if: ${{ inputs.add-changelog }}
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}

      - run: echo "" > CHANGELOG.md
        if: ${{ ! inputs.add-changelog }}

      - uses: actions/download-artifact@v4
        with:
          pattern: release-*
          merge-multiple: true

      - id: build-name
        run: |
          TAG="$GAME_NAME-${{ github.ref_name }}"
          if [ ! -z "$BRANCH" ]; then
            TAG="$TAG-$BRANCH"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "name=Release $GAME_NAME ${{github.ref_name}} $BRANCH" >> $GITHUB_OUTPUT
        env:
          GAME_NAME: ${{ inputs.name }}
          BRANCH: ${{ inputs.branch }}

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          prerelease: false
          name: ${{ steps.build-name.outputs.name }}
          tag_name: ${{ steps.build-name.outputs.tag }}
          files: |
            **/*.7z
      
      - name: Successful release!
        if: success()
        uses: ./discord
        with:
          discord-webhook: ${{ secrets.discord-webhook }}
          title: "${{ inputs.name }} - New Release ${{ github.ref_name }} ${{ inputs.branch }}"
          message: "${{ steps.changelog.outputs.changelog }} \n\nPassword: ${{ secrets.password }}\n${{ steps.release.outputs.url }}"

      - name: Failed release!
        if: failure()
        uses: ./discord
        with:
          discord-webhook: ${{ secrets.discord-webhook }}
          title: "${{ inputs.name }} - Failed Release ${{ github.ref_name }} ${{ inputs.branch }}"
          message: "See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          failure: true