name: Build Godot Templates

on:
  workflow_call:
    inputs:
      version:
        description: 'Godot version'
        required: true
        type: string
        default: '4.3'
      platforms:
        description: 'Target platforms.'
        required: true
        type: string
        default: '["linuxbsd", "windows", "web"]'
  workflow_dispatch:
    inputs:
      version:
        description: 'Godot version'
        required: true
        type: string
        default: '4.3'
      platforms:
        description: 'Target platforms.'
        required: true
        type: string
        default: '["linuxbsd", "windows", "web"]'

jobs:
  template-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ${{ fromJSON(inputs.products)}}
    steps:
      - id: encryption
        run: echo "key=$(openssl rand -hex 32)" >> $GITHUB_OUTPUT

      - uses: kuma-gee/action-godot/godot-template@main
        with:
          version: ${{ inputs.version }}
          platform: ${{ matrix.platform }}
          encryption-key: ${{ steps.encryption.outputs.key }}

      - uses: actions/upload-artifact@v4
        with:
          name: template-${{ matrix.platform }}
          path: bin/*
        
        # TODO: restart release if this was called from a release workflow

  release-godot-template:
    runs-on: ubuntu-latest
    needs: template-build
    steps:
      - uses: ./.github/workflows/github-release.yml
        with:
          artifact: template-*
          password: ${{ secrets.GODOT_ASSETS_PASSWORD }}
          name: Template