name: Build Godot Templates

on:
  push:
    tags:
      - template-v[0-9]+

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  template-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linuxbsd, windows, web]
    steps:
      - uses: actions/checkout@v4
      - uses: kuma-gee/action-godot/godot-template@main
        with:
          version: ${{ env.GODOT_VERSION }}
          platform: ${{ matrix.platform }}
          encryption-key: ${{ secrets.ENCRYPTION_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: template-${{ matrix.platform }}
          path: bin/*

  release-godot-template:
    runs-on: ubuntu-latest
    needs: template-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          pattern: template-*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: bin/*
          name: Godot ${{ inputs.version }} Templates