name: Build Godot Templates

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  template-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]
    steps:
      - uses: actions/checkout@v4
      - uses: kuma-gee/action-godot/godot-template@main
        if: ${{ ! inputs.debug }}
        with:
          version: ${{ vars.GODOT_VERSION }}
          platform: ${{ matrix.platform }}
          encryption-key: ${{ secrets.ENCRYPTION_KEY }}

      - run: touch godot/bin/$PLATFORM_release
        if: ${{ inputs.debug }}
        env:
          PLATFORM: ${{ matrix.platform }}

      - uses: actions/upload-artifact@v4
        with:
          name: template-${{ matrix.platform }}
          path: godot/bin/*

  release-godot-template:
    runs-on: ubuntu-latest
    needs: template-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          pattern: template-*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: bin/*
          name: Godot ${{ vars.GODOT_VERSION }} Templates
          tag_name: template-${{ vars.GODOT_VERSION }}