name: Build Godot Templates

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Godot version'
        required: true
        type: string
        default: '4.3'

jobs:
  generate-encryption:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      key: ${{ steps.encryption.outputs.key }}
    steps:
      - id: encryption
        run: |
          KEY="$(openssl rand -hex 32)"
          gh secret set ENCRYPTION_KEY -b $KEY
          echo "key=$KEY" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  template-build:
    runs-on: ubuntu-latest
    needs: generate-encryption
    strategy:
      matrix:
        platform: [linuxbsd, windows, web]
    steps:
      - uses: kuma-gee/action-godot/godot-template@main
        with:
          version: ${{ inputs.version }}
          platform: ${{ inputs.platform }}
          encryption-key: ${{ needs.generate-encryption.outputs.key }}

      - uses: actions/upload-artifact@v4
        with:
          name: template-${{ matrix.platform }}
          path: bin/*

  release-godot-template:
    runs-on: ubuntu-latest
    needs: template-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          pattern: template-*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: bin/*
          name: Godot ${{ inputs.version }} Templates