name: Itch Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GAME: godot-game
  GODOT_VERSION: 4.3
  STEAM_APP: 430

jobs:
  generate-password:
    runs-on: ubuntu-latest
    outputs:
      password: ${{ steps.random-password.outputs.password }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/password
        id: random-password
        with:
          length: 16

  release-itch:
    runs-on: ubuntu-latest
    needs: generate-password
    container:
      image: barichello/godot-ci:4.3
    strategy:
      matrix:
        channel: [web, win, linux]
    env:
      CHANNEL: ${{matrix.channel}}
    steps:
      - uses: actions/checkout@v4

      - name: Publish Itch
        shell: bash
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          USER: ${{ secrets.ITCHIO_USER }}
        run: butler push build/$CHANNEL $USER/$GAME:$CHANNEL --userversion $GITHUB_REF_NAME

      - name: Package builds
        run: |
          cd build
          mv $CHANNEL $GAME
          zip -e -r $GAME-$CHANNEL.zip $GAME -P $PASSWORD
        env:
          PASSWORD: ${{ needs.generate-password.outputs.password }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.channel }}
          path: build/**/*.zip

  release-itch-github:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: ./.github/workflows/github-release.yml
        with:
          artifact: release-*
          password: ${{ secrets.GODOT_ASSETS_PASSWORD }}