name: Steam Release

on:
  workflow_call:
    inputs:
      steam-app:
        description: 'Steam App ID'
        type: number
        required: true
      branch:
        description: 'Steam branch to release'
        type: string
        default: 'beta'
    secrets:
      STEAM_USERNAME:
        description: 'Steam username'
        required: false 
      STEAM_CONFIG_VDF:
        description: 'Steam config.vdf'
        required: false
      PASSWORD:
        description: 'Password for the files'
        required: false

jobs:
  release-steam:
    runs-on: ubuntu-latest
    steps:
      - uses: kuma-gee/action-godot/fetch-release@main
        with:
          artifacts: release-*
          password: ${{ secrets.PASSWORD }}
          output: build

      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
          appId: ${{ inputs.steam-app }}
          buildDescription: ${{ github.ref_name }}
          rootPath: build
          depot1Path: windows
          depot2Path: linux
          releaseBranch: ${{ inputs.branch }}