name: Steam Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deployToSteam:
      runs-on: ubuntu-latest
      steps:
        - uses: CyberAndrii/steam-totp@v1
          name: Generate TOTP
          id: steam-totp
          with:
            shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}
        - uses: game-ci/steam-deploy@v3
          with:
            username: ${{ secrets.STEAM_USERNAME }}          
            totp: ${{ steps.steam-totp.outputs.code }}
            appId: 1234560
            buildDescription: v1.2.3
            rootPath: build
            depot1Path: StandaloneWindows64
            depot2Path: StandaloneLinux64
            releaseBranch: prerelease