name: Steam Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GODOT_VERSION: 4.3
  STEAM_APP: 430

jobs:
  generate-password:
    runs-on: ubuntu-latest
    outputs:
      password: ${{ steps.random-password.outputs.password }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/password
        id: random-password
        with:
          length: 16

  release-steam:
    runs-on: ubuntu-latest
    needs: generate-password
    container:
      image: barichello/godot-ci:4.3
    strategy:
      matrix:
        channel: [web, windows, linuxbsd]
    steps:
      - uses: actions/checkout@v4

      - uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: template-${{ matrix.channel }}

      - uses: ./.github/workflows/godot-template-build.yml
        with:
          version: $env.GODOT_VERSION
          platforms: '["${{ matrix.channel }}"]'

      - uses: ./.github/workflows/godot-build.yml
        with:
          channel: ${{ matrix.channel }}
          assets-password: ${{ secrets.GODOT_ASSETS_PASSWORD }}
          zip-password: ${{ needs.generate-password.outputs.password }}
          game-code: ${{ secrets.GAME_CODE }}
          output: godot-game/build
          steam-app: $env.STEAM_APP

      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
          appId: $env.STEAM_APP
          buildDescription: $GITHUB_REF_NAME
          rootPath: build
          depot1Path: StandaloneWindows64
          depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
          depot2Path: StandaloneLinux64
          releaseBranch: prerelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.channel }}
          path: build/**/*.zip

  release-steam-github:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: ./.github/workflows/github-release.yml
        with:
          artifact: release-*
          name: $env.GAME_NAME