name: Steam Release

on:
  workflow_call:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: false
      demo:
        description: 'Release demo'
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: false
      demo:
        description: 'Release demo'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  generate-password:
    runs-on: ubuntu-latest
    outputs:
      password: ${{ steps.random-password.outputs.password }}
    steps:
      - uses: actions/checkout@v4
      - uses: kuma-gee/action-godot/password@main
        id: random-password
        with:
          length: 24

  release-steam:
    runs-on: ubuntu-latest
    needs: [generate-password]
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    strategy:
      matrix:
        include:
          - channel: windows
            depotId: 1
          - channel: linux
            depotId: 2
    steps:
      - uses: actions/checkout@v4

      - name: Unpack protected assets
        uses: kuma-gee/action-protect-assets@v1
        with:
          path: ${{ vars.PROJECT_PATH }}/assets
          password: ${{ secrets.ASSETS_PASSWORD }}

      - name: Create Godot Environment File
        uses: kuma-gee/action-godot/godot-env@main
        with:
          output: ${{ vars.PROJECT_PATH }}/build.gd
          code: ${{ secrets.GAME_CODE }}
          version: ${{ github.ref }}
          steam-app: ${{ vars.STEAM_APP }}

      - name: Setup Templates
        uses: kuma-gee/action-godot/setup-template@main
        with:
          version: ${{ vars.GODOT_VERSION }}
          channel: ${{ matrix.channel }}
          encryption-key: ${{ secrets.ENCRYPTION_KEY }}
          game-folder: ${{ vars.PROJECT_PATH }}

      - uses: kuma-gee/action-godot/godot-build@main
        with:
          channel: ${{ matrix.channel }}
          output: build
          game-folder: ${{ vars.PROJECT_PATH }}
          password: ${{ needs.generate-password.outputs.password }}
      
      - id: steam-app
        run: |
          STEAM_ID=$MAIN_ID
          if [ $DEMO = true ]; then
            STEAM_ID=$DEMO_ID
          fi

          echo "id=$STEAM_ID" >> $GITHUB_OUTPUT
        env:
          DEMO: ${{ github.event.inputs.demo }}
          MAIN_ID: ${{ vars.STEAM_APP }}
          DEMO_ID: ${{ vars.STEAM_DEMO_APP }}

      - uses: game-ci/steam-deploy@v3
        if: github.event.inputs.branch != ''
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
          appId: ${{ steps.steam-app.outputs.id }}
          buildDescription: ${{ github.ref_name }}
          rootPath: build
          depot${{matrix.depotId}}Path: ${{ matrix.channel }}
          releaseBranch: ${{ github.event.inputs.branch }}
      
      - run: ls build
        if: failure()

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.channel }}
          path: build/*

  release-steam-github:
    needs: [release-steam, generate-password]
    uses: kuma-gee/action-godot/.github/workflows/github-release.yml@main
    if: github.event.inputs.release-discord == true
    with:
      artifact: release-*
      branch: ${{ inputs.branch }}
    secrets:
      discord-webhook: ${{ secrets.DISCORD_RELEASE_HOOK }}
      password: ${{ needs.generate-password.outputs.password }}