name: Test Godot Env

on:
  push:
    paths:
      - godot-env/**
    branches:
      - main

jobs:
  test-godot-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./godot-env
        with:
          output: build.gd
          code: secret-game-code
          version: v1.0
          steam-app: 12345
      - run: |
          if ! grep -q v1.0 "$File"; then
            echo "::error::Game Version missing in file"
            exit 1
          elif ! grep -q $EXPECTED_HASH "$File"; then
            echo "::error::Game Hash missing in file"
            exit 1
          elif ! grep -q 12345 "$File"; then
            echo "::error::Steam App Id missing in file"
            exit 1
          fi
        shell: bash
        env:
          File: build.gd
          EXPECTED_HASH: bccc92b5f6c23cd6c5df292f608632278e0605f8540afeee9d258f7a2a8a6087