name: Test Fetch Release

on:
  push:
    paths:
      - fetch-release/**
    branches:
      - main

jobs:
  upload-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [windows, linux]
    steps:
      - run: |
          mkdir -p build/
          echo $CHANNEL > build/main

          zip -r amazing-game-$CHANNEL.zip build/* -e -P $PASSWORD
        env:
          CHANNEL: ${{ matrix.channel }}
          PASSWORD: 123

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: releases-${{ matrix.channel }}
          path: '*.zip'

  test-fetch-release:
    runs-on: ubuntu-latest
    needs: upload-files
    steps:
      - uses: actions/checkout@v4

      - uses: ./fetch-release
        with:
          artifacts: releases-*
          password: 123
          output: releases
      
      - run: |
          if [ ! -d releases/windows ]; then
            echo "Windows folder not found"
            exit 1
          fi

          if [ ! -d releases/linux ]; then
            echo "Linux folder not found"
            exit 1
          fi