name: Test Password

on:
  push:
    paths:
      - password/**
    branches:
      - main
  
jobs:
  test-password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./password
        id: random-password-1
        with:
          length: 5
      - uses: ./password
        id: random-password-2
        with:
          length: 10
      - uses: ./password
        id: random-password-3
        with:
          length: 100
      - run: |
          echo "::debug::Generated password: $password1, $password2, $password3"

          if [ ${#password1} -ne 5 ]; then
            echo "::error::Password length is not 5"
            exit 1
          fi

          if [ ${#password2} -ne 10 ]; then
            echo "::error::Password length is not 10"
            exit 1
          fi

          if [ ${#password3} -ne 100 ]; then
            echo "::error::Password length is not 100"
            exit 1
          fi

          if [ "$password1" == "$password2" ]; then
            echo "::error::Passwords 1 and 2 are the same"
            exit 1
          fi

          if [ "$password1" == "$password3" ]; then
            echo "::error::Passwords 1 and 3 are the same"
            exit 1
          fi

          if [ "$password2" == "$password3" ]; then
            echo "::error::Passwords 2 and 3 are the same"
            exit 1
          fi
        shell: bash
        env:
          password1: ${{ steps.random-password-1.outputs.password }}
          password2: ${{ steps.random-password-2.outputs.password }}
          password3: ${{ steps.random-password-3.outputs.password }}
